package utils

import (
	"fmt"
	"os"
	"path/filepath"
	breadTypes "yoheiyayoi/bread/pkg/bread_type"

	"github.com/BurntSushi/toml"
)

// Functions

// Get bread.lock path
func LockfilePath() (string, error) {
	projectPath, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getting current directory: %w", err)
	}

	return filepath.Join(projectPath, "bread.lock"), nil
}

func LoadLockfile(lockfileData *breadTypes.Lockfile) error {
	lockPath, err := LockfilePath()
	if err != nil {
		return fmt.Errorf("getting lockfile path: %w", err)
	}

	if _, err := toml.DecodeFile(lockPath, &lockfileData); err == nil {
		return nil
	}

	return fmt.Errorf("failed to load bread.lock file")
}

func SaveLockfile(lockfile breadTypes.Lockfile) error {
	path, err := LockfilePath()
	if err != nil {
		return fmt.Errorf("getting lockfile path: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create lockfile: %w", err)
	}
	defer file.Close()

	header := "# This file is automatically @generated by Bread.\n# It is not intended for manual editing.\n\n"
	if _, err := file.WriteString(header); err != nil {
		return fmt.Errorf("failed to write lockfile header: %w", err)
	}

	if err := toml.NewEncoder(file).Encode(lockfile); err != nil {
		return fmt.Errorf("failed to write lockfile: %w", err)
	}

	return nil
}
