package utils

import (
	"archive/zip"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// Functions
func ParsePackageSpec(name, versionSpec string) (packageName, version string) {
	if parts := strings.SplitN(versionSpec, "@", 2); len(parts) == 2 {
		return parts[0], parts[1]
	}
	// If versionSpec looks like "author/repo", assume it's the package name and version is empty (latest)
	if strings.Contains(versionSpec, "/") {
		return versionSpec, ""
	}
	return name, versionSpec
}

func getPackageName(name string) string {
	if parts := strings.Split(name, "/"); len(parts) == 2 {
		return parts[1]
	}
	return name
}

func packageIDFileName(name, version string) string {
	parts := strings.Split(name, "/")
	if len(parts) == 2 {
		return fmt.Sprintf("%s_%s@%s", parts[0], parts[1], version) // author/repo@version
	}
	return fmt.Sprintf("%s@%s", name, version) // repo@version
}

func (ic *InstallationContext) downloadPackage(name, version string, realm string) error {
	url := fmt.Sprintf("https://api.wally.run/v1/package-contents/%s/%s", name, version)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return err
	}

	req.Header.Set("User-Agent", "bread/1.0")
	req.Header.Set("Accept", "application/octet-stream")
	req.Header.Set("Wally-Version", "0.3.2")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		if resp.StatusCode == http.StatusNotFound {
			return fmt.Errorf("package %s@%s not found", name, version)
		}
		return fmt.Errorf("failed to download %s@%s: HTTP %d", name, version, resp.StatusCode)
	}

	tmpFile, err := os.CreateTemp("", "package-*.zip")
	if err != nil {
		return err
	}
	defer func() {
		tmpFile.Close()
		os.Remove(tmpFile.Name())
	}()

	if _, err := io.Copy(tmpFile, resp.Body); err != nil {
		return err
	}

	packageDirName := packageIDFileName(name, version)
	targetDir := filepath.Join(ic.getIndexDir(realm), packageDirName)

	return unzipPackage(tmpFile.Name(), targetDir, name)
}

// This code still generated by AI, if this can be improved, please tell me in discord or send a pull request
func unzipPackage(src, dest, packageName string) error {
	r, err := zip.OpenReader(src)
	if err != nil {
		return err
	}
	defer r.Close()

	packageDir := filepath.Join(dest, getPackageName(packageName))
	if err := os.MkdirAll(packageDir, 0755); err != nil {
		return err
	}

	for _, f := range r.File {
		// Compute safe path
		fpath := filepath.Join(packageDir, f.Name)

		// Zip Slip protection (standard pattern)
		if !strings.HasPrefix(fpath, filepath.Clean(packageDir)+string(os.PathSeparator)) {
			return fmt.Errorf("illegal file path in archive: %s", f.Name)
		}

		fi := f.FileInfo()
		if !fi.Mode().IsRegular() && !fi.IsDir() {
			return fmt.Errorf("unsupported file type in archive: %s (mode %v)", f.Name, fi.Mode())
		}

		// Ensure parent directories exist
		if err := os.MkdirAll(filepath.Dir(fpath), 0755); err != nil {
			return err
		}

		if fi.IsDir() {
			// Create directory with entry's permissions (or fallback to 0755)
			if err := os.MkdirAll(fpath, fi.Mode().Perm()|0755); err != nil {
				return err
			}
			// Optionally chmod if needed (MkdirAll already used perm)
			continue
		}

		// Extract regular file
		if err := extractFile(f, fpath); err != nil {
			return err
		}

		// Preserve permissions and timestamp
		if err := os.Chmod(fpath, fi.Mode().Perm()); err != nil {
			return err
		}
		if !f.Modified.IsZero() {
			if err := os.Chtimes(fpath, f.Modified, f.Modified); err != nil {
				return err
			}
		}
	}
	return nil
}

func extractFile(f *zip.File, destPath string) error {
	outFile, err := os.OpenFile(destPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode().Perm())
	if err != nil {
		return err
	}
	defer outFile.Close()

	rc, err := f.Open()
	if err != nil {
		return err
	}
	defer rc.Close()

	_, err = io.Copy(outFile, rc)
	return err
}
